on:
  # Trigger the workflow on push, but only for the dev branch
  push:
    branches:
      - master
name: build-and-deploy

jobs:
  build:
    timeout-minutes: 5
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Yarn for build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Create .env file
        run: echo $VUE_APP_GMAPSKEY | tr " " "\n" >> .env
      - run: echo "$(<.env )"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Run deploy script
        run: |
          git config user.name "kniazevgeny" && git config user.email "eugene.kniazev@gmail.com"
          git checkout --orphan gh-pages
          sudo mv dist/echarge/* dist/
          git --work-tree dist add --all
          git --work-tree dist commit -m gh-pages
          git push origin HEAD:gh-pages --force