on:
  # Trigger the workflow on push, but only for the dev branch
  push:
    branches:
      - master
name: build

jobs:
  build-and-deploy:
    timeout-minutes: 5
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Run deploy script
        run: |
          git config user.name "kniazevgeny" && git config user.email "eugene.kniazev@gmail.com"
          yarn gh-pages-deploy